require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0.3
  TargetRailsVersion: 7.0.1
  Include:
    -  'app/**/*'
    - 'config.ru'
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'spec/**/*'
  Exclude:
    - 'app/views/**/*'
    - 'app/assets/**/*'
    - 'app/javascript/**/*'
    - 'app/services/item_parsers/**/*'
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'scripts/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Guardfile'

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'

Rails:
  Enabled: true

RSpec/NestedGroups:
  Enabled: false

RSpec/LetSetup:
  Enabled: false